Repository terraform-providers/terraform-provider-skytap, pull requests merged in 2019-01, with the labels that each got.

#8 Fix documentation errors
  website/docs/r/network.html.md
  website/docs/r/vm.html.md
Labels: documentation, size/XS

#6 Add CPU and RAM settings to VM resource
  GNUmakefile
  skytap/resource_skytap_environment.go
  skytap/resource_skytap_project.go
  skytap/resource_skytap_vm.go
  skytap/resource_skytap_vm_test.go
  vendor/github.com/skytap/skytap-sdk-go/skytap/vm.go
  vendor/vendor.json
  website/docs/r/vm.html.md
Labels: dependencies, documentation, enhancement, size/L

#10 #2 Add disk create to VM resource
  skytap/resource_skytap_vm.go
  skytap/resource_skytap_vm_test.go
  skytap/structures.go
  skytap/structures_test.go
  skytap/testdata/disks.json
  vendor/github.com/skytap/skytap-sdk-go/skytap/vm.go
  vendor/vendor.json
  website/docs/r/vm.html.md
Labels: dependencies, documentation, size/XL

#14 #3 Allow update for CPU and RAM setting on VM resource
  skytap/resource_skytap_vm.go
  skytap/resource_skytap_vm_hardware_test.go
  vendor/github.com/skytap/skytap-sdk-go/skytap/vm.go
  vendor/vendor.json
Labels: dependencies, enhancement, size/M

#15 #2 Disk resize ability on the VM resource
  skytap/resource_skytap_vm.go
  skytap/resource_skytap_vm_hardware_test.go
  skytap/structures.go
  vendor/github.com/skytap/skytap-sdk-go/skytap/vm.go
  vendor/vendor.json
  website/docs/r/vm.html.md
Labels: dependencies, documentation, enhancement, size/XL

#16 #2 Add OS disk resizing to VM resource
  skytap/resource_skytap_vm.go
  skytap/resource_skytap_vm_hardware_test.go
  vendor/github.com/skytap/skytap-sdk-go/skytap/vm.go
  vendor/vendor.json
Labels: dependencies, documentation, enhancement, size/XL

#19 #7 Add map for published service ports and IPs
  skytap/config.go
  skytap/resource_skytap_vm.go
  skytap/resource_skytap_vm_test.go
  skytap/structures.go
  skytap/structures_test.go
  skytap/testdata/vm_interface_ports_response.json
  skytap/testdata/vm_interface_response.json
  skytap/testdata/vm_interface_services_response.json
  skytap/utils/utils.go
  vendor/github.com/skytap/skytap-sdk-go/skytap/published_service.go
  vendor/vendor.json
Labels: dependencies, documentation, enhancement, size/XL

#20 Improve tests and documentation
  GNUmakefile
  skytap/data_source_skytap_template_test.go
  skytap/resource_skytap_environment_test.go
  skytap/resource_skytap_network_test.go
  skytap/resource_skytap_vm.go
  skytap/resource_skytap_vm_hardware_test.go
  skytap/resource_skytap_vm_test.go
  skytap/structures.go
  skytap/utils/utils.go
  vendor/github.com/skytap/skytap-sdk-go/skytap/vm.go
  vendor/vendor.json
  website/docs/r/vm.html.md
Labels: bug, dependencies, documentation, size/XL, technical-debt

#22 Update project.html.md
  website/docs/r/project.html.md
Labels: documentation, size/XS

#23 Update project.html.md (#22)
  website/docs/r/project.html.md
Labels: documentation, size/XS

#21 Code reliability improvements
  skytap/config.go
  skytap/resource_skytap_environment.go
  skytap/resource_skytap_network.go
  skytap/resource_skytap_project.go
  skytap/resource_skytap_vm.go
  skytap/resource_skytap_vm_hardware_test.go
  skytap/resource_skytap_vm_test.go
  skytap/structures.go
  skytap/utils/response.go
  skytap/utils/utils.go
  vendor/github.com/skytap/skytap-sdk-go/skytap/vm.go
  vendor/vendor.json
Labels: dependencies, documentation, enhancement, size/XXL, technical-debt

#24 Update CHANGELOG.md
  CHANGELOG.md
Labels: size/XS

#25 [AUTOMATED] Upgrade to Go 1.11
  .travis.yml
Labels: size/XS
